name: Per-commit

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    env:
      node-version: 12.x
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - id: find-yarn-cache-dir
      name: Find Yarn cache directory
      run: echo "::set-output name=result::$(yarn cache dir)"
    - name: Cache Node.js modules
      run: echo "${{ steps.find-yarn-cache-dir.outputs.result }}"
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
